######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 9 19:55:16 2009
######################################################################


QT       -= gui
TARGET = readShared
CONFIG   += console

TEMPLATE = app

# Input
HEADERS += SharedMemory.h
SOURCES += main.cpp SharedMemory.cpp



MOC_DIR		   = obj
OBJECTS_DIR    = obj
